mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('polls/', include('polls.urls'), name='polls'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/polls/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('user/<int:pk>/', views.UserDetailView.as_view(template_name='polls/user-detail.html'),
         name='user-detail'),
    path('user/<int:pk>/update-user/', views.UpdateUserView.as_view(), name='update-user'),
    path('user/<int:pk>/delete-user/', views.DeleteUserView.as_view(), name='delete-user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class AuthUser(AbstractUser):
    avatar = models.ImageField(upload_to='polls/media/avatars', blank=False)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_votes = models.IntegerField(default=0)
    description = models.TextField(max_length=600)

    image = models.ImageField(upload_to='polls/media/questions')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    def get_percentage(self):
        percents = round(self.votes * 100 / self.question.question_votes, 2)
        return percents

class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)

mysite/polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import AuthUser


class SignupForm(UserCreationForm):

    class Meta:
        model = AuthUser
        fields = ('username', 'password1', 'password2', 'avatar')

mysite/polls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from .models import Question, Choice, AuthUser, Vote
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import SignupForm

from django.shortcuts import render, redirect, get_object_or_404


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Выберете один из пунктов'
        })
    if Vote.objects.filter(question=question, user=request.user).exists():
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Выбор уже сделан'
        })
    else:
        question.question_votes += 1
        question.save()
        selected_choice.votes += 1
        selected_choice.save()
        user_voted = Vote.objects.create(question=question, user=request.user)
        user_voted.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class SignupView(generic.CreateView):
    model = AuthUser
    form_class = SignupForm
    template_name = 'polls/signup.html'
    success_url = reverse_lazy('login')
    success_page = "polls"


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = AuthUser


class UpdateUserView(LoginRequiredMixin, generic.UpdateView):
    model = AuthUser
    form_class = SignupForm
    template_name = 'polls/update-user.html'
    success_url = '/'


class DeleteUserView(LoginRequiredMixin, generic.DeleteView):
    model = AuthUser
    template_name = 'polls/delete-user.html'
    success_url = '/'

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Polls</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body class="lead col-xs-offset-1">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10">
            {% block content %}
            <ul>
                     {% if user.is_authenticated %}

                <li style="list-style-type: none;"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>

                {% else %}

                <li style="list-style-type: none;"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                <li style="list-style-type: none;"><a href="{% url 'polls:signup'%}?next={{request.path}}">Sign Up</a>
                </li>

                {% endif %}
            </ul>

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

<style>
    input[type=submit] {
    margin-top: 5px;
    padding: 5px 10px;
    background-color: #80669d;
    color: white;
    border: none;
    border-radius: 5px;
    }
    .flex {
    display: flex;
    gap: 200px;
    }
    img {
    max-height: 300px
    }
</style>

mysite/polls/templates/polls/delete-user.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="section-seperator">
    <div class="content-md container">
        <div class="row margin-b-40">
            <div class="col-sm-6">
                <h2>Удаление аккаунта {{ authuser }}</h2>
                <p>Вы действительно хотите удалить свой аккаунт?</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Да, удалить."/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <div class="flex">
         <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        <p>{{question.description}}</p>
        {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
    <img src="{{question.image.url}}" alt="">
    </div>
<input type="submit" value="Vote">
</form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<br>
{% if user.is_authenticated %}

<div class="" role="alert">
    <ul class="sidebar-nav">
        <li style="list-style-type: none;"><a href="{% url 'polls:user-detail' request.user.id %}">User: {{ user.get_username }}</a></li>
    </ul>
</div>
<a class="a2" href="{% url 'logout' %}">Logout</a>

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    {% if question.was_published_recently or user.is_superuser %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
    {{question.description|truncatechars:30}}
    {% endif %}
    {% endfor %}
</ul>

{% else %}
<p>
    Нет вопросов!
</p>


{% endif %}

{% else %}
<div class="" role="alert">
    <h1>Welcome to Home!</h1>
</div>
{% endif %}
<br>
<div class="center">
    {% if not user.is_authenticated %}
    <a class="a1" href="{% url 'polls:signup'%}?next={{request.path}}">Sign Up</a>
    <a class="a2" href="{% url 'login' %}">Login</a>
    {% endif %}
</div>
{% endblock content %}





mysite/polls/templates/polls/login.html
{% extends 'users/base.html' %}

{% block content %}
  <br>
  <div class="" role="alert">
    <h2 style="text-align: center;">Login</h2>
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock content%}

mysite/polls/templates/polls/logout.html
{% extends 'users/base.html' %}

{% block content %}
    <br>
    <div class="" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">Login</a> <br>
    <a href="{% url 'home' %}">Or go back to home-page.</a>
{% endblock content %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>

    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}} - {{ choice.get_percentage }}%</li>

    {% endfor %}
</ul>
<a href="{% url 'polls:index'  %}"> Вернуться </a>

mysite/polls/templates/polls/signup.html
{% extends 'polls/base.html' %}

{% block content %}
    <br>
    <div role="alert">
        <h2 style="text-align: center;">Sign Up</h2>
    </div>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        <button type="submit" class="media">Sign up</button>
    </form>
{% endblock content%}

mysite/polls/templates/polls/update-user.html
{% extends 'polls/base.html' %}

{% block content %}
    <br>
    <div role="alert">
        <h2 style="text-align: center;">Update data</h2>
    </div>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

mysite/polls/templates/polls/updateDataUser.html
{% extends 'polls/base.html' %}

{% block content %}
    <br>
    <div role="alert">
        <h2 style="text-align: center;">Update data</h2>
    </div>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

mysite/polls/templates/polls/user-detail.html
{% extends "polls/base.html" %}

{% block content %}
<h1> {{ authuser }}</h1>
{% if authuser.avatar %}
<img style="width: 250px" src="/polls{{ authuser.avatar.url }}" alt="user's avatar">
{% endif %}
{% if authuser == request.user %}
<ul class="sidebar-nav">
    <li style="list-style-type: none;"><a href="./update-user/">Update profile</a></li>
    <li style="list-style-type: none;"><a href="./delete-user/">Delete user</a></li>
</ul>
{% endif %}
{% endblock %}